parameters:
    swd_shard.migrations: ~
services:
#  _defaults:
   # autoconfigure: true

  Swd\Bundle\ShardBundle\Command\:
    resource: '../../Command/*'
    exclude: '../../Command/*{Helper,Trait}.php'
    tags:
      - console.command

#    swd_shard.example:
#        class: Swd\Bundle\DoctrineShardBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
